### ISSUE TITLE
Cached node_modules layer reused on rebuild even when package.json has changed

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/yarn-install#143]
## What happened?

I used `pack` to build an [app](https://github.com/paketo-buildpacks/samples/tree/main/nodejs/yarn); then changed the version of a dependency in the `package.json`. When I rebuilt the app, the cached layer containing the `node_modules` was reused, and I got a stale version of the desired dependency.

* What did you expect to happen?

I expected the app to be rebuilt with the new version of the dependency.

* What was the actual behavior? Please provide log output, if possible.

First build:
```
pack build change-package-json  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.17-base --clear-cache
0.1.17-base: Pulling from paketobuildpacks/builder
Digest: sha256:33c46f75dd199d80423e6a96ecbd44586d87fa0a12c96806aeb0d17495bdab3b
Status: Image is up to date for paketobuildpacks/builder:0.1.17-base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:33d37fc9ba16e220f071805eaeed881a508ceee5c8909db5710aaed7e97e4fc2
Status: Image is up to date for paketobuildpacks/run:base-cnb
0.0.10: Pulling from paketo-buildpacks/nodejs
Digest: sha256:4b723c77e6313b7d283fc0e1c2745979a88930935b05f9a2268023b3cb45d7db
Status: Image is up to date for gcr.io/paketo-buildpacks/nodejs:0.0.10
0.9.3: Pulling from buildpacksio/lifecycle
Digest: sha256:bc253af2edf1577717618cb3a95f0f16bb18fc9e804efbcc1b85f657d931a757
Status: Image is up to date for buildpacksio/lifecycle:0.9.3
===> DETECTING
[detector] paketo-buildpacks/node-engine  0.1.2
[detector] paketo-buildpacks/yarn         0.0.2
[detector] paketo-buildpacks/yarn-install 0.2.0
[detector] paketo-buildpacks/yarn-start   0.0.2
===> ANALYZING
[analyzer] Warning: Not restoring cached layer metadata, no cache flag specified.
[analyzer] Previous image with name "index.docker.io/library/change-package-json:latest" not found
[analyzer] Skipping buildpack layer analysis
===> RESTORING
Skipping 'restore' due to clearing cache
===> BUILDING
[builder] Paketo Node Engine Buildpack 0.1.2
[builder]   Resolving Node Engine version
[builder]     Candidate version sources (in priority order):
[builder]                 -> ""
[builder]       <unknown> -> "*"
[builder]
[builder]     Selected Node Engine version (using ): 10.22.1
[builder]
[builder]   Executing build process
[builder]     Installing Node Engine 10.22.1
[builder]       Completed in 1.262s
[builder]
[builder]   Configuring environment
[builder]     NODE_ENV     -> "production"
[builder]     NODE_HOME    -> "/layers/paketo-buildpacks_node-engine/node"
[builder]     NODE_VERBOSE -> "false"
[builder]
[builder]     Writing profile.d/0_memory_available.sh
[builder]       Calculates available memory based on container limits at launch time.
[builder]       Made available in the MEMORY_AVAILABLE environment variable.
[builder]
[builder] Paketo Yarn Buildpack 0.0.2
[builder]   Executing build process
[builder]     Installing Yarn
[builder]       Completed in 173ms
[builder]
[builder] Paketo Yarn Install Buildpack 0.2.0
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       yarn.lock -> Found
[builder]
[builder]     Selected default build process: 'yarn install'
[builder]
[builder]   Executing build process
[builder]     Running yarn install --ignore-engines --frozen-lockfile --modules-folder /layers/paketo-buildpacks_yarn-install/modules/node_modules
[builder]       Completed in 1.856s
[builder]
[builder]   Configuring environment
[builder]     PATH -> "$PATH:/layers/paketo-buildpacks_yarn-install/modules/node_modules/.bin"
[builder] Paketo Yarn Start Buildpack 0.0.2
[builder]   Assigning launch processes
[builder]     web: node server.js
[builder]
===> EXPORTING
[exporter] Adding layer 'paketo-buildpacks/node-engine:node'
[exporter] Adding layer 'paketo-buildpacks/yarn-install:modules'
[exporter] Adding 1/1 app layer(s)
[exporter] Adding layer 'launcher'
[exporter] Adding layer 'config'
[exporter] Adding layer 'process-types'
[exporter] Adding label 'io.buildpacks.lifecycle.metadata'
[exporter] Adding label 'io.buildpacks.build.metadata'
[exporter] Adding label 'io.buildpacks.project.metadata'
[exporter] Setting default process type 'web'
[exporter] *** Images (ea08a008264e):
[exporter]       index.docker.io/library/change-package-json:latest
[exporter] Adding cache layer 'paketo-buildpacks/node-engine:node'
[exporter] Adding cache layer 'paketo-buildpacks/yarn:yarn'
[exporter] Adding cache layer 'paketo-buildpacks/yarn-install:modules'
Successfully built image change-package-json
```
then, changed the version constraint in the `package.json` and rebuilt:
```
pack build change-package-json  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.17-base
0.1.17-base: Pulling from paketobuildpacks/builder
Digest: sha256:33c46f75dd199d80423e6a96ecbd44586d87fa0a12c96806aeb0d17495bdab3b
Status: Image is up to date for paketobuildpacks/builder:0.1.17-base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:33d37fc9ba16e220f071805eaeed881a508ceee5c8909db5710aaed7e97e4fc2
Status: Image is up to date for paketobuildpacks/run:base-cnb
0.0.10: Pulling from paketo-buildpacks/nodejs
Digest: sha256:4b723c77e6313b7d283fc0e1c2745979a88930935b05f9a2268023b3cb45d7db
Status: Image is up to date for gcr.io/paketo-buildpacks/nodejs:0.0.10
0.9.3: Pulling from buildpacksio/lifecycle
Digest: sha256:bc253af2edf1577717618cb3a95f0f16bb18fc9e804efbcc1b85f657d931a757
Status: Image is up to date for buildpacksio/lifecycle:0.9.3
===> DETECTING
[detector] paketo-buildpacks/node-engine  0.1.2
[detector] paketo-buildpacks/yarn         0.0.2
[detector] paketo-buildpacks/yarn-install 0.2.0
[detector] paketo-buildpacks/yarn-start   0.0.2
===> ANALYZING
[analyzer] Restoring metadata for "paketo-buildpacks/node-engine:node" from app image
[analyzer] Restoring metadata for "paketo-buildpacks/yarn:yarn" from cache
[analyzer] Restoring metadata for "paketo-buildpacks/yarn-install:modules" from app image
===> RESTORING
[restorer] Restoring data for "paketo-buildpacks/node-engine:node" from cache
[restorer] Restoring data for "paketo-buildpacks/yarn:yarn" from cache
[restorer] Restoring data for "paketo-buildpacks/yarn-install:modules" from cache
===> BUILDING
[builder] Paketo Node Engine Buildpack 0.1.2
[builder]   Resolving Node Engine version
[builder]     Candidate version sources (in priority order):
[builder]                 -> ""
[builder]       <unknown> -> "*"
[builder]
[builder]     Selected Node Engine version (using ): 10.22.1
[builder]
[builder]   Reusing cached layer /layers/paketo-buildpacks_node-engine/node
[builder]
[builder] Paketo Yarn Buildpack 0.0.2
[builder]   Reusing cached layer /layers/paketo-buildpacks_yarn/yarn
[builder]
[builder] Paketo Yarn Install Buildpack 0.2.0
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       yarn.lock -> Found
[builder]
[builder]     Selected default build process: 'yarn install'
[builder]
[builder]   Reusing cached layer /layers/paketo-buildpacks_yarn-install/modules
[builder] Paketo Yarn Start Buildpack 0.0.2
[builder]   Assigning launch processes
[builder]     web: node server.js
[builder]
===> EXPORTING
[exporter] Reusing layer 'paketo-buildpacks/node-engine:node'
[exporter] Reusing layer 'paketo-buildpacks/yarn-install:modules'
[exporter] Adding 1/1 app layer(s)
[exporter] Reusing layer 'launcher'
[exporter] Reusing layer 'config'
[exporter] Reusing layer 'process-types'
[exporter] Adding label 'io.buildpacks.lifecycle.metadata'
[exporter] Adding label 'io.buildpacks.build.metadata'
[exporter] Adding label 'io.buildpacks.project.metadata'
[exporter] Setting default process type 'web'
[exporter] *** Images (fbec1140f6e4):
[exporter]       index.docker.io/library/change-package-json:latest
[exporter] Reusing cache layer 'paketo-buildpacks/node-engine:node'
[exporter] Reusing cache layer 'paketo-buildpacks/yarn:yarn'
[exporter] Reusing cache layer 'paketo-buildpacks/yarn-install:modules'
Successfully built image change-package-json
```
## Build Configuration

Please provide some details about your build configuration.

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you using? Please include a version.
```
pack --version
0.13.1+git-4134cc6.build-1135
```
* What buildpacks are you using? Please include versions.

(see above log output for versions used)

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

(see above log output for versions used)

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

I used [this sample app](https://github.com/paketo-buildpacks/samples/tree/main/nodejs/yarn). Before first build, I set the version constraint for the express dependency in `package.json`:
```
   "dependencies": {
       "express": "4.17.0"
   },
```
and re-generated the `yarn.lock` file.

Before second build, I changed the `package.json` to contain:
```
   "dependencies": {
       "express": "4.17.1"
   },
```
**but did not re-generate the `yarn.lock` file**.

## Checklist

Please confirm the following:

* [x] I have included log output.
* [ ] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by fg-j** [comment]
If subsequently force the cache to be cleared
```
pack build change-package-json  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.17-base --clear-cache
```
the build fails with the error
```
 [builder]   Executing build process
[builder]     Running yarn install --ignore-engines --frozen-lockfile --modules-folder /layers/paketo-buildpacks_yarn-install/modules/node_modules
[builder] failed to execute yarn install: exit status 1
[builder]       yarn install v1.22.4
[builder]       [1/4] Resolving packages...
[builder]       error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
[builder]       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[builder]
[builder]
[builder] ERROR: failed to build: exit status 1
```
since the `package.json` and `yarn.lock` have not been synced.

**Comment by arjun024** [comment]
Thank you @fg-j  for the detailed report.

The supported way to manage dependencies is via yarn commands, as stated in [the official documentation](https://classic.yarnpkg.com/en/docs/managing-dependencies). The `yarn add` command will modify the `yarn.lock` thereby invalidating the cache. I understand that this is not obvious from the current behavior of the buildpack. To that regard, I think the following should be done:

(1) Add documentation detailing expected workflow
(2) Making the build fail with explicit error if `package.json` and `yarn.lock` are out of sync (using [yarn check](https://classic.yarnpkg.com/en/docs/cli/check/#toc-yarn-check))

Does that sound reasonable to you?

**Comment by arjun024** [comment]
As a part of this, it should be investigated if we invalidate the cache on changes to parts of `package.json` other than `dependencies` (For e.g. adding a `postinstall` script)

**Comment by fg-j** [comment]
@arjun024 What about the use-case where I have a post-install script that I want to run on every build (say, something that generates some static files in the working dir) but sometimes it doesn't run because the `yarn-install` step doesn't run?

**Comment by arjun024** [comment]
@fg-j Yes I believe we should only skip re-running "yarn install" if `package.json` is also unchanged.
https://github.com/paketo-buildpacks/yarn-install/blob/v0.2.5/install_process.go#L80 should consider package.json as well. Does that make sense?

**Comment by fg-j** [comment]
The case I'm thinking about is slightly different. Suppose you have a fixed `package.json` that always contains some
```
{
  "scripts": {
       "postinstall" : ng build
  }
}
```
where `ng build` generates some static assets into the build working directory. Those static assets aren't persisted between buildpack builds because they build into the workspace, not into a layer.

Now, suppose I rebuild my app without changing my `package.json`. I still want to run `ng build` to generate my static assets, but the buildpack notices no change to the lockfiles (or to the `package.json`) and so it skips running `yarn install` entirely. My `ng build` never runs; my static assets aren't regenerated on rebuilds.

This seems like an issue that _may_ be addressed by the proposed [node-run-scripts buildpack](https://github.com/paketo-buildpacks/nodejs/blob/main/rfcs/0004-npm-scripts.md).

However, I don't think that specific problem would be solved just by invalidating the cache when the `package.json` changes.

**Comment by fg-j** [comment]
Does the node run scripts buildpack actually ameliorate this problem? Maybe this isn't actually a bug? @arjun024 Any thoughts?

**Comment by arjun024** [comment]
@fg-j node run scripts buildpack will only come into play when a user manually sets `BP_NODE_RUN_SCRIPTS`. In all other case, I believe this issue still persists

**Comment by c0d1ngm0nk3y** [comment]
This issue is rather old, but it is still present. Although you could argue if it is an issue at all. The `yarn.lock` is not changed, so you get the dependencies you have locked. Doesn't sound that wrong to me.

I had a look how `npm-install` is handling this case and there the `sha` for the cache does not only contain the the `package-lock.json`, but also `package.json`. So if one of the files changes, the cache won't be reused. I guess the same could work with `yarn`.

@paketo-buildpacks/nodejs-maintainers WDYT?

**Comment by mhdawson** [comment]
@c0d1ngm0nk3y I think the same approach of having the sha for the cache include both the `package.lock` and `package.json` makes sense to be consistent across npm-install and yarn-install buildpacks.
